# --- Config ---

# Screen
WIDTH, HEIGHT = 800, 600
FPS = 60

# Player
PLAYER_SIZE = 20
PLAYER_SPEED = 4
BASE_PLAYER_SPEED = 4
BASE_ATTACK_COOLDOWN = 800
ATTACK_RADIUS = 120
ATTACK_LINE_DURATION = 100

# Player Health / Regen
PLAYER_BASE_HP = 100
REGEN_AMOUNT = 3
REGEN_INTERVAL_MS = 2000

# Enemy
ENEMY_SIZE = 20
ENEMY_SPEED = 2
ENEMY_SPAWN_TIME = 1500
MIN_SPAWN_TIME = 300
SPAWN_OFFSET = 40
STRONG_ENEMY_CHANCE = 0.20
STRONG_ENEMY_HP = 4
ENEMY_ATTACK_DAMAGE = 5
STRONG_ENEMY_EXP_MULT = 3

# XP and Level
XP_PER_KILL = 1
XP_BASE = 5
MAX_PERCENT_UPGRADE = 0.02

# Game states
PLAYING = 0
GAME_OVER = 1
LEVEL_UP = 2
MENU = 3
